// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GC2CS.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GC2CS {

  /// <summary>Holder for reflection information generated from GC2CS.proto</summary>
  public static partial class GC2CSReflection {

    #region Descriptor
    /// <summary>File descriptor for GC2CS.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GC2CSReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtHQzJDUy5wcm90bxIFR0MyQ1MaEFJlc3VsdENvZGUucHJvdG8qxAEKBU1z",
            "Z0lkEgkKBUZpcnN0EAASCgoFQmVnaW4QyGUSGwoWR0MyQ1NfRW50ZXJHYW1l",
            "U2VydmljZRDJZRITCg5HQzJDU19IZXJvTGlzdBCtZhIXChJHQzJDU19BZGRI",
            "ZXJvTGV2ZWwQrmYSHQoYR0MyQ1NfTm90aWZ5VXBkYXRlSGVyb2VzEK9mEhoK",
            "FUdDMkNTX1N0YXJ0TWF0ZUNvbWJhdBDKZhIUCg9HQzJDU19Db21iYXRFbmQQ",
            "y2YSCAoDRW5kELxpYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ResultCodeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GC2CS.MsgId), }, null));
    }
    #endregion

  }
  #region Enums
  public enum MsgId {
    [pbr::OriginalName("First")] First = 0,
    [pbr::OriginalName("Begin")] Begin = 13000,
    /// <summary>
    /// User
    /// </summary>
    [pbr::OriginalName("GC2CS_EnterGameService")] Gc2CsEnterGameService = 13001,
    /// <summary>
    /// Hero
    /// </summary>
    [pbr::OriginalName("GC2CS_HeroList")] Gc2CsHeroList = 13101,
    [pbr::OriginalName("GC2CS_AddHeroLevel")] Gc2CsAddHeroLevel = 13102,
    [pbr::OriginalName("GC2CS_NotifyUpdateHeroes")] Gc2CsNotifyUpdateHeroes = 13103,
    /// <summary>
    /// Mate
    /// </summary>
    [pbr::OriginalName("GC2CS_StartMateCombat")] Gc2CsStartMateCombat = 13130,
    [pbr::OriginalName("GC2CS_CombatEnd")] Gc2CsCombatEnd = 13131,
    [pbr::OriginalName("End")] End = 13500,
  }

  #endregion

}

#endregion Designer generated code
