// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cmd.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NetProto {

  /// <summary>Holder for reflection information generated from Cmd.proto</summary>
  public static partial class CmdReflection {

    #region Descriptor
    /// <summary>File descriptor for Cmd.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CmdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CglDbWQucHJvdG8SCE5ldFByb3RvKo0MCghQcm90b0lEcxIJCgVGaXJzdBAA",
            "EhAKDENoZWNrTG9naW4yUxBlEg8KC0VudGVyR2FtZTJTEGYSEwoPUmVnaXN0",
            "QWNjb3VudDJTEGcSFgoSUmVnaXN0ZXJHYXRlQWRkcjJTEGgSGAoTQXBwbHlD",
            "cmVhdGVCYXR0bGUyUxDJARIXChJUcmFuc2l0aW9uQmF0dGxlMlMQrQISHgoZ",
            "VHJhbnNpdGlvbkJhdHRsZTJQbGF5ZXIyUxCuAhIWChFOb3RpZnlCYXR0bGVF",
            "bmQyUxCvAhIPCgpDaGVja0xvZ2luENEPEg4KCUVudGVyR2FtZRDSDxISCg1S",
            "ZWdpc3RBY2NvdW50ENMPEhEKDFN5bmNNYWluVGFzaxDaDxIYChNGaW5pc2hN",
            "YWluVGFza1N0YWdlENsPEhkKFFJlY2VpdmVNYWluVGFza1J3YXJkENwPEgwK",
            "B1N5bmNCYWcQ5A8SDwoKVXBkYXRlSXRlbRDlDxIRCgxTeW5jSGVyb0xpc3QQ",
            "7g8SEwoOVXBkYXRlSGVyb0xpc3QQ7w8SFQoQVXBncmFkZUhlcm9MZXZlbBDw",
            "DxIUCg9HZXRUZWFtUm9vbUxpc3QQlhASEwoOQ3JlYXRlVGVhbVJvb20QlxAS",
            "EgoNTGVhdmVUZWFtUm9vbRCYEBISCg1FbnRlclRlYW1Sb29tEJkQEh4KGVNl",
            "bGVjdFRlYW1TdGFnZUluVGVhbVJvb20QmhASHAoXU2VsZWN0VXNlSGVyb0lu",
            "VGVhbVJvb20QmxASHwoaQ2hhbmdlUmVhZHlTdGF0ZUluVGVhbVJvb20QnBAS",
            "FAoPU3RhcnRUZWFtQmF0dGxlEJ0QEhgKE05vdGlmeUxlYXZlVGVhbVJvb20Q",
            "pRASHgoZTm90aWZ5UGxheWVyRW50ZXJUZWFtUm9vbRCmEBIdChhOb3RpZnlD",
            "aGFuZ2VUZWFtUm9vbUluZm8QpxASJQogTm90aWZ5Q2hhbmdlUGxheWVySW5m",
            "b0luVGVhbVJvb20QqBASFQoQQXBwbHlFbnRlckJhdHRsZRC0EBIYChNBcHBs",
            "eUhlcm9FeGFtQmF0dGxlELUQEhgKE0FwcGx5TWFpblRhc2tCYXR0bGUQthAS",
            "FwoSTm90aWZ5Q3JlYXRlQmF0dGxlELkXEhcKElBsYXllckxvYWRQcm9ncmVz",
            "cxC6FxIeChlOb3RpZnlBbGxQbGF5ZXJMb2FkRmluaXNoELsXEhYKEUJhdHRs",
            "ZVJlYWR5RmluaXNoELwXEhYKEU5vdGlmeUJhdHRsZVN0YXJ0EL0XEg8KCk1v",
            "dmVFbnRpdHkQnRgSDQoIVXNlU2tpbGwQnhgSEgoNQ2xpZW50UGxvdEVuZBC6",
            "GBIZChROb3RpZnlDcmVhdGVFbnRpdGllcxCBGRIZChROb3RpZnlFbnRpdHlT",
            "dG9wTW92ZRCDGRIdChhOb3RpZnlFbnRpdHlSZWxlYXNlU2tpbGwQhBkSHAoX",
            "Tm90aWZ5Q3JlYXRlU2tpbGxFZmZlY3QQhRkSHwoaTm90aWZ5U2tpbGxFZmZl",
            "Y3RTdGFydE1vdmUQhhkSHQoYTm90aWZ5U2tpbGxFZmZlY3REZXN0cm95EIcZ",
            "EhkKFE5vdGlmeVN5bmNFbnRpdHlBdHRyEIgZEhoKFU5vdGlmeVN5bmNFbnRp",
            "dHlWYWx1ZRCJGRIVChBOb3RpZnlFbnRpdHlEZWFkEIoZEhMKDk5vdGlmeVBs",
            "YXlQbG90EIwZEhIKDU5vdGlmeVBsb3RFbmQQjRkSHQoYTm90aWZ5U2V0RW50",
            "aXR5U2hvd1N0YXRlEI4ZEhQKD05vdGlmeUVudGl0eURpchCPGRIbChZOb3Rp",
            "ZnlFbnRpdHlNb3ZlQnlQYXRoEJAZEhoKFU5vdGlmeVNraWxsSW5mb1VwZGF0",
            "ZRCRGRIfChpOb3RpZnlOb3RpZnlVcGRhdGVCdWZmSW5mbxCSGRIVChBUcmFu",
            "c2l0aW9uQmF0dGxlEOUZEhwKF1RyYW5zaXRpb25CYXR0bGUyUGxheWVyEOYZ",
            "EhMKDkFwcGx5QmF0dGxlRW5kEPgZEhQKD05vdGlmeUJhdHRsZUVuZBD5GWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::NetProto.ProtoIDs), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ProtoIDs {
    [pbr::OriginalName("First")] First = 0,
    /// <summary>
    /// 1 -- 2000 服务端----------------------------------------------
    /// </summary>
    [pbr::OriginalName("CheckLogin2S")] CheckLogin2S = 101,
    [pbr::OriginalName("EnterGame2S")] EnterGame2S = 102,
    [pbr::OriginalName("RegistAccount2S")] RegistAccount2S = 103,
    [pbr::OriginalName("RegisterGateAddr2S")] RegisterGateAddr2S = 104,
    [pbr::OriginalName("ApplyCreateBattle2S")] ApplyCreateBattle2S = 201,
    [pbr::OriginalName("TransitionBattle2S")] TransitionBattle2S = 301,
    [pbr::OriginalName("TransitionBattle2Player2S")] TransitionBattle2Player2S = 302,
    [pbr::OriginalName("NotifyBattleEnd2S")] NotifyBattleEnd2S = 303,
    /// <summary>
    /// 2000+ 客户端--------------------------------------------------
    /// </summary>
    [pbr::OriginalName("CheckLogin")] CheckLogin = 2001,
    [pbr::OriginalName("EnterGame")] EnterGame = 2002,
    [pbr::OriginalName("RegistAccount")] RegistAccount = 2003,
    /// <summary>
    /// 主线任务
    /// </summary>
    [pbr::OriginalName("SyncMainTask")] SyncMainTask = 2010,
    [pbr::OriginalName("FinishMainTaskStage")] FinishMainTaskStage = 2011,
    [pbr::OriginalName("ReceiveMainTaskRward")] ReceiveMainTaskRward = 2012,
    /// <summary>
    /// 背包
    /// </summary>
    [pbr::OriginalName("SyncBag")] SyncBag = 2020,
    [pbr::OriginalName("UpdateItem")] UpdateItem = 2021,
    /// <summary>
    /// 英雄
    /// </summary>
    [pbr::OriginalName("SyncHeroList")] SyncHeroList = 2030,
    [pbr::OriginalName("UpdateHeroList")] UpdateHeroList = 2031,
    [pbr::OriginalName("UpgradeHeroLevel")] UpgradeHeroLevel = 2032,
    /// <summary>
    /// 组队
    /// </summary>
    [pbr::OriginalName("GetTeamRoomList")] GetTeamRoomList = 2070,
    [pbr::OriginalName("CreateTeamRoom")] CreateTeamRoom = 2071,
    [pbr::OriginalName("LeaveTeamRoom")] LeaveTeamRoom = 2072,
    [pbr::OriginalName("EnterTeamRoom")] EnterTeamRoom = 2073,
    [pbr::OriginalName("SelectTeamStageInTeamRoom")] SelectTeamStageInTeamRoom = 2074,
    [pbr::OriginalName("SelectUseHeroInTeamRoom")] SelectUseHeroInTeamRoom = 2075,
    [pbr::OriginalName("ChangeReadyStateInTeamRoom")] ChangeReadyStateInTeamRoom = 2076,
    [pbr::OriginalName("StartTeamBattle")] StartTeamBattle = 2077,
    [pbr::OriginalName("NotifyLeaveTeamRoom")] NotifyLeaveTeamRoom = 2085,
    [pbr::OriginalName("NotifyPlayerEnterTeamRoom")] NotifyPlayerEnterTeamRoom = 2086,
    [pbr::OriginalName("NotifyChangeTeamRoomInfo")] NotifyChangeTeamRoomInfo = 2087,
    [pbr::OriginalName("NotifyChangePlayerInfoInTeamRoom")] NotifyChangePlayerInfoInTeamRoom = 2088,
    /// <summary>
    /// 战斗入口
    /// </summary>
    [pbr::OriginalName("ApplyEnterBattle")] ApplyEnterBattle = 2100,
    /// <summary>
    /// 即将舍去
    /// </summary>
    [pbr::OriginalName("ApplyHeroExamBattle")] ApplyHeroExamBattle = 2101,
    /// <summary>
    /// 主线
    /// </summary>
    [pbr::OriginalName("ApplyMainTaskBattle")] ApplyMainTaskBattle = 2102,
    /// <summary>
    /// 战斗开始流程
    /// </summary>
    [pbr::OriginalName("NotifyCreateBattle")] NotifyCreateBattle = 3001,
    [pbr::OriginalName("PlayerLoadProgress")] PlayerLoadProgress = 3002,
    [pbr::OriginalName("NotifyAllPlayerLoadFinish")] NotifyAllPlayerLoadFinish = 3003,
    [pbr::OriginalName("BattleReadyFinish")] BattleReadyFinish = 3004,
    [pbr::OriginalName("NotifyBattleStart")] NotifyBattleStart = 3005,
    /// <summary>
    /// 玩家操作
    /// </summary>
    [pbr::OriginalName("MoveEntity")] MoveEntity = 3101,
    [pbr::OriginalName("UseSkill")] UseSkill = 3102,
    [pbr::OriginalName("ClientPlotEnd")] ClientPlotEnd = 3130,
    /// <summary>
    /// 服务端发来的关键战斗事件(转发)
    /// </summary>
    [pbr::OriginalName("NotifyCreateEntities")] NotifyCreateEntities = 3201,
    /// <summary>
    /// NotifyEntityMove = 3202; //废弃
    /// </summary>
    [pbr::OriginalName("NotifyEntityStopMove")] NotifyEntityStopMove = 3203,
    [pbr::OriginalName("NotifyEntityReleaseSkill")] NotifyEntityReleaseSkill = 3204,
    [pbr::OriginalName("NotifyCreateSkillEffect")] NotifyCreateSkillEffect = 3205,
    [pbr::OriginalName("NotifySkillEffectStartMove")] NotifySkillEffectStartMove = 3206,
    [pbr::OriginalName("NotifySkillEffectDestroy")] NotifySkillEffectDestroy = 3207,
    [pbr::OriginalName("NotifySyncEntityAttr")] NotifySyncEntityAttr = 3208,
    [pbr::OriginalName("NotifySyncEntityValue")] NotifySyncEntityValue = 3209,
    [pbr::OriginalName("NotifyEntityDead")] NotifyEntityDead = 3210,
    [pbr::OriginalName("NotifyPlayPlot")] NotifyPlayPlot = 3212,
    [pbr::OriginalName("NotifyPlotEnd")] NotifyPlotEnd = 3213,
    [pbr::OriginalName("NotifySetEntityShowState")] NotifySetEntityShowState = 3214,
    [pbr::OriginalName("NotifyEntityDir")] NotifyEntityDir = 3215,
    [pbr::OriginalName("NotifyEntityMoveByPath")] NotifyEntityMoveByPath = 3216,
    [pbr::OriginalName("NotifySkillInfoUpdate")] NotifySkillInfoUpdate = 3217,
    [pbr::OriginalName("NotifyNotifyUpdateBuffInfo")] NotifyNotifyUpdateBuffInfo = 3218,
    /// <summary>
    /// 转发战斗
    /// </summary>
    [pbr::OriginalName("TransitionBattle")] TransitionBattle = 3301,
    [pbr::OriginalName("TransitionBattle2Player")] TransitionBattle2Player = 3302,
    /// <summary>
    /// 主动申请战斗结束(一般是本地战斗)
    /// </summary>
    [pbr::OriginalName("ApplyBattleEnd")] ApplyBattleEnd = 3320,
    [pbr::OriginalName("NotifyBattleEnd")] NotifyBattleEnd = 3321,
  }

  #endregion

}

#endregion Designer generated code
