// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cmd.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NetProto {

  /// <summary>Holder for reflection information generated from Cmd.proto</summary>
  public static partial class CmdReflection {

    #region Descriptor
    /// <summary>File descriptor for Cmd.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CmdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CglDbWQucHJvdG8SCE5ldFByb3RvKscFCghQcm90b0lEcxIJCgVGaXJzdBAA",
            "EhAKDENoZWNrTG9naW4yUxBlEg8KC0VudGVyR2FtZTJTEGYSEwoPUmVnaXN0",
            "QWNjb3VudDJTEGcSGAoTQXBwbHlDcmVhdGVCYXR0bGUyUxDJARIXChJUcmFu",
            "c2l0aW9uQmF0dGxlMlMQrQISHgoZVHJhbnNpdGlvbkJhdHRsZTJQbGF5ZXIy",
            "UxCuAhIPCgpDaGVja0xvZ2luENEPEg4KCUVudGVyR2FtZRDSDxISCg1SZWdp",
            "c3RBY2NvdW50ENMPEhgKE0FwcGx5SGVyb0V4YW1CYXR0bGUQtBASFwoSTm90",
            "aWZ5Q3JlYXRlQmF0dGxlELkXEhcKElBsYXllckxvYWRQcm9ncmVzcxC6FxIe",
            "ChlOb3RpZnlBbGxQbGF5ZXJMb2FkRmluaXNoELsXEhYKEUJhdHRsZVJlYWR5",
            "RmluaXNoELwXEhYKEU5vdGlmeUJhdHRsZVN0YXJ0EL0XEg8KCk1vdmVFbnRp",
            "dHkQnRgSDQoIVXNlU2tpbGwQnhgSGQoUTm90aWZ5Q3JlYXRlRW50aXRpZXMQ",
            "gRkSFQoQTm90aWZ5RW50aXR5TW92ZRCCGRIZChROb3RpZnlFbnRpdHlTdG9w",
            "TW92ZRCDGRIdChhOb3RpZnlFbnRpdHlSZWxlYXNlU2tpbGwQhBkSHAoXTm90",
            "aWZ5Q3JlYXRlU2tpbGxFZmZlY3QQhRkSHwoaTm90aWZ5U2tpbGxFZmZlY3RT",
            "dGFydE1vdmUQhhkSHQoYTm90aWZ5U2tpbGxFZmZlY3REZXN0cm95EIcZEhkK",
            "FE5vdGlmeVN5bmNFbnRpdHlBdHRyEIgZEhoKFU5vdGlmeVN5bmNFbnRpdHlW",
            "YWx1ZRCJGRIVChBUcmFuc2l0aW9uQmF0dGxlEOUZEhwKF1RyYW5zaXRpb25C",
            "YXR0bGUyUGxheWVyEOYZYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::NetProto.ProtoIDs), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ProtoIDs {
    [pbr::OriginalName("First")] First = 0,
    /// <summary>
    /// 1 -- 2000 服务端-----
    /// </summary>
    [pbr::OriginalName("CheckLogin2S")] CheckLogin2S = 101,
    [pbr::OriginalName("EnterGame2S")] EnterGame2S = 102,
    [pbr::OriginalName("RegistAccount2S")] RegistAccount2S = 103,
    [pbr::OriginalName("ApplyCreateBattle2S")] ApplyCreateBattle2S = 201,
    [pbr::OriginalName("TransitionBattle2S")] TransitionBattle2S = 301,
    [pbr::OriginalName("TransitionBattle2Player2S")] TransitionBattle2Player2S = 302,
    /// <summary>
    /// 2000+ 客户端-----
    /// </summary>
    [pbr::OriginalName("CheckLogin")] CheckLogin = 2001,
    [pbr::OriginalName("EnterGame")] EnterGame = 2002,
    [pbr::OriginalName("RegistAccount")] RegistAccount = 2003,
    /// <summary>
    /// 战斗入口
    /// </summary>
    [pbr::OriginalName("ApplyHeroExamBattle")] ApplyHeroExamBattle = 2100,
    /// <summary>
    /// 战斗开始流程
    /// </summary>
    [pbr::OriginalName("NotifyCreateBattle")] NotifyCreateBattle = 3001,
    [pbr::OriginalName("PlayerLoadProgress")] PlayerLoadProgress = 3002,
    [pbr::OriginalName("NotifyAllPlayerLoadFinish")] NotifyAllPlayerLoadFinish = 3003,
    [pbr::OriginalName("BattleReadyFinish")] BattleReadyFinish = 3004,
    [pbr::OriginalName("NotifyBattleStart")] NotifyBattleStart = 3005,
    /// <summary>
    /// 玩家操作
    /// </summary>
    [pbr::OriginalName("MoveEntity")] MoveEntity = 3101,
    [pbr::OriginalName("UseSkill")] UseSkill = 3102,
    /// <summary>
    /// 服务端发来的关键战斗事件
    /// </summary>
    [pbr::OriginalName("NotifyCreateEntities")] NotifyCreateEntities = 3201,
    [pbr::OriginalName("NotifyEntityMove")] NotifyEntityMove = 3202,
    [pbr::OriginalName("NotifyEntityStopMove")] NotifyEntityStopMove = 3203,
    [pbr::OriginalName("NotifyEntityReleaseSkill")] NotifyEntityReleaseSkill = 3204,
    [pbr::OriginalName("NotifyCreateSkillEffect")] NotifyCreateSkillEffect = 3205,
    [pbr::OriginalName("NotifySkillEffectStartMove")] NotifySkillEffectStartMove = 3206,
    [pbr::OriginalName("NotifySkillEffectDestroy")] NotifySkillEffectDestroy = 3207,
    [pbr::OriginalName("NotifySyncEntityAttr")] NotifySyncEntityAttr = 3208,
    [pbr::OriginalName("NotifySyncEntityValue")] NotifySyncEntityValue = 3209,
    /// <summary>
    /// 转发战斗
    /// </summary>
    [pbr::OriginalName("TransitionBattle")] TransitionBattle = 3301,
    [pbr::OriginalName("TransitionBattle2Player")] TransitionBattle2Player = 3302,
  }

  #endregion

}

#endregion Designer generated code
