// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GC2SS.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GC2SS {

  /// <summary>Holder for reflection information generated from GC2SS.proto</summary>
  public static partial class GC2SSReflection {

    #region Descriptor
    /// <summary>File descriptor for GC2SS.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GC2SSReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtHQzJTUy5wcm90bxIFR0MyU1MaEFJlc3VsdENvZGUucHJvdG8qqgIKBU1z",
            "Z0lkEgkKBUZpcnN0EAASCwoFQmVnaW4Q6IQBEh4KGEdDMlNTX1N5bmNDb21i",
            "YXRJbml0SW5mbxDphAESIgocR0MyU1NfUGxheWVyTG9hZENvbWJhdEZpbmlz",
            "aBDqhAESGwoVR0MyU1NfU3luY0NvbWJhdFN0YXJ0EOuEARIZChNHQzJTU19T",
            "eW5jQ29tYmF0RW5kEOyEARIYChJHQzJTU19Ob3JtYWxBdHRhY2sQ7YQBEiAK",
            "GkdDMlNTX1N5bmNSb3VuZEFjdGlvblN0YXJ0EO6EARIhChtHQzJTU19Db21i",
            "YXRQbGF5ZXJPcGVyYXRpb24Q74QBEiMKHUdDMlNTX1N5bmNUaW1lbGluZUFs",
            "bFNlcXVlbmNlEPCEARIJCgNFbmQQ3IgBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ResultCodeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GC2SS.MsgId), }, null));
    }
    #endregion

  }
  #region Enums
  public enum MsgId {
    [pbr::OriginalName("First")] First = 0,
    [pbr::OriginalName("Begin")] Begin = 17000,
    /// <summary>
    /// 同步战斗初始信息
    /// </summary>
    [pbr::OriginalName("GC2SS_SyncCombatInitInfo")] Gc2SsSyncCombatInitInfo = 17001,
    /// <summary>
    /// 客户端加载战斗完成
    /// </summary>
    [pbr::OriginalName("GC2SS_PlayerLoadCombatFinish")] Gc2SsPlayerLoadCombatFinish = 17002,
    /// <summary>
    /// 战斗开始
    /// </summary>
    [pbr::OriginalName("GC2SS_SyncCombatStart")] Gc2SsSyncCombatStart = 17003,
    /// <summary>
    /// 战斗结束
    /// </summary>
    [pbr::OriginalName("GC2SS_SyncCombatEnd")] Gc2SsSyncCombatEnd = 17004,
    /// <summary>
    /// 普通攻击(作废)
    /// </summary>
    [pbr::OriginalName("GC2SS_NormalAttack")] Gc2SsNormalAttack = 17005,
    /// <summary>
    /// 回合开始
    /// </summary>
    [pbr::OriginalName("GC2SS_SyncRoundActionStart")] Gc2SsSyncRoundActionStart = 17006,
    /// <summary>
    /// 该回合操作完成
    /// </summary>
    [pbr::OriginalName("GC2SS_CombatPlayerOperation")] Gc2SsCombatPlayerOperation = 17007,
    /// <summary>
    /// 发送所有英雄在这回合的 timeline
    /// </summary>
    [pbr::OriginalName("GC2SS_SyncTimelineAllSequence")] Gc2SsSyncTimelineAllSequence = 17008,
    [pbr::OriginalName("End")] End = 17500,
  }

  #endregion

}

#endregion Designer generated code
